// import homeImg from "../assets/home_square.png";

export const packages = [
  {
    image: "home_square",
    id: 1,
    user_id: 2,
    price: 50,
    category: 1,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 50,
    availability: true,
  },
  {
    image: "home_square",
    id: 2,
    user_id: 2,
    price: 60,
    category: 2,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 100,
    availability: true,
  },
  {
    image: "home_square",
    id: 3,
    user_id: 3,
    price: 70,
    category: 3,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 150,
    availability: true,
  },
  {
    image: "home_square",
    id: 4,
    user_id: 3,
    price: 80,
    category: 4,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 200,
    availability: true,
  },{
    image: "home_square",
    id: 5,
    user_id: 2,
    price: 50,
    category: 1,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 50,
    availability: true,
  },
  {
    image: "home_square",
    id: 6,
    user_id: 2,
    price: 60,
    category: 2,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 100,
    availability: true,
  },
  {
    image: "home_square",
    id: 7,
    user_id: 3,
    price: 70,
    category: 3,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 150,
    availability: true,
  },
  {
    image: "home_square",
    id: 8,
    user_id: 3,
    price: 80,
    category: 4,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 200,
    availability: true,
  },{
    image: "home_square",
    id: 9,
    user_id: 2,
    price: 50,
    category: 1,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 50,
    availability: true,
  },
  {
    image: "home_square",
    id: 10,
    user_id: 2,
    price: 60,
    category: 2,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 100,
    availability: true,
  },
  {
    image: "home_square",
    id: 11,
    user_id: 3,
    price: 70,
    category: 3,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 150,
    availability: true,
  },
  {
    image: "home_square",
    id: 12,
    user_id: 3,
    price: 80,
    category: 4,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 200,
    availability: true,
  },{
    image: "home_square",
    id: 13,
    user_id: 2,
    price: 50,
    category: 1,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 50,
    availability: true,
  },
  {
    image: "home_square",
    id: 14,
    user_id: 2,
    price: 60,
    category: 2,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 100,
    availability: true,
  },
  {
    image: "home_square",
    id: 15,
    user_id: 3,
    price: 70,
    category: 3,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 150,
    availability: true,
  },
  {
    image: "home_square",
    id: 16,
    user_id: 3,
    price: 80,
    category: 4,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 200,
    availability: true,
  },{
    image: "home_square",
    id: 17,
    user_id: 2,
    price: 50,
    category: 1,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 50,
    availability: true,
  },
  {
    image: "home_square",
    id: 18,
    user_id: 2,
    price: 60,
    category: 2,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 100,
    availability: true,
  },
  {
    image: "home_square",
    id: 19,
    user_id: 3,
    price: 70,
    category: 3,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 150,
    availability: true,
  },
  {
    image: "home_square",
    id: 20,
    user_id: 3,
    price: 80,
    category: 4,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
    tent_description: "This is my tent",
    bags_description: "This is my sleeping bag(s)",
    lantern_description: "This is my lantern",
    cooking_description: "This is my cooking",
    location: 200,
    availability: true,
  },
];

// module.exports = { packages };
