INSERT INTO items (id, user_id, price, category, description, tent_description, bags_description, lantern_description,
    cooking_description, location )
VALUES

("product_page.png",1,1,50,1,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",295),
("product_page.png",2,2,60,2,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",27),
("product_page.png",3,3,70,3,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",68),
("product_page.png",4,4,80,4,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",54),
("product_page.png",5,5,50,1,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",73),
("product_page.png",6,1,60,2,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",71),
("product_page.png",7,2,70,3,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",196),
("product_page.png",8,3,80,4,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",118),
("product_page.png",9,4,50,1,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",209),
("product_page.png",10,5,60,2,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",125),
("product_page.png",11,1,70,3,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",16),
("product_page.png",12,2,80,4,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",71),
("product_page.png",13,3,50,1,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",213),
("product_page.png",14,4,60,2,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",108),
("product_page.png",15,5,70,3,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries","This is my tent","This is my sleeping bag(s)","This is my lantern","This is my cooking",10),