INSERT INTO
packages (home_img, package_img, booking_img, user_id, price, category, description, tent_description, bags_description, lantern_description, cooking_description, latitude, longitude)
VALUES
('home_01','package_01','booking_01',1,50,1,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',43.687775, -79.388245),
('home_02','package_02','booking_02',2,60,2,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',43.696333, -79.404032),
('home_03','package_03','booking_03',3,70,3,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',43.681266,-79.404204),
('home_04','package_04','booking_04',4,80,4,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',43.685678,-79.443177),
('home_05','package_05','booking_05',5,50,1,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',43.688041,-79.336635),
('home_06','package_06','booking_06',1,60,2,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',43.684031,-79.373762),
('home_07','package_07','booking_07',2,70,3,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',43.699909,-79.391671),
('home_08','package_08','booking_08',3,80,4,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',43.693813,-79.398023),
('home_09','package_09','booking_09',4,50,1,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',43.695666, -79.412008),
('home_10','package_10','booking_10',5,60,2,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',43.692856,-79.336915),
('home_11','package_11','booking_11',1,70,3,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',43.688088,-79.401521),
('home_12','package_12','booking_12',2,80,4,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',43.685521,-79.404826);


