INSERT INTO packages (image, user_id, price, category, description, tent_description, bags_description, lantern_description,
    cooking_description, location )
VALUES
('home_square',1,50,1,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',295),
('home_square',2,60,2,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',27),
('home_square',3,70,3,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',68),
('home_square',4,80,4,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',54),
('home_square',5,50,1,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',73),
('home_square',1,60,2,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',71),
('home_square',2,70,3,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',196),
('home_square',3,80,4,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',118),
('home_square',4,50,1,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',209),
('home_square',5,60,2,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',125),
('home_square',1,70,3,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',16),
('home_square',2,80,4,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',71),
('home_square',3,50,1,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',213),
('home_square',4,60,2,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',108),
('home_square',5,70,3,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries','This is my tent','This is my sleeping bag(s)','This is my lantern','This is my cooking',10);